### PR TITLE
week2 task finished.

### PR DESCRIPTION
**Pull request by WilliamTsai1227**
蔡廷威
http://34.223.129.79:8000/

### CODE REVIEW

**Comment by WilliamTsai1227** [comment]
蔡廷威
http://34.223.129.79:8000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
If we click on MRT name, our code should fill input element and **do keyword search immediately.**

**Comment by WilliamTsai1227** [comment]
Fixed the issue where when clicking on the MRT name, our code should fill in the input element and do keyword search immediately.

**Comment by WilliamTsai1227** [comment]
@cwpeng I have made the requested changes. Thank you teacher!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
